# Generated by Django 6.0.1 on 2026-01-12 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_propertyrecord_latitude_propertyrecord_longitude'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedlenskartstore',
            name='source_ppt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stores', to='property.propertyrecord', verbose_name='Source PPT'),
        ),
    ]
