# Generated by Django 6.0.1 on 2026-01-12 10:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_propertyrecord_latitude_propertyrecord_longitude'),
        ('store', '0002_approvedlenskartstore_source_ppt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvedlenskartstore',
            options={'ordering': ['-property_id'], 'verbose_name': 'Approved Lenskart Store', 'verbose_name_plural': 'Approved Lenskart Stores'},
        ),
        migrations.AddField(
            model_name='approvedlenskartstore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvedlenskartstore',
            name='ppt_file',
            field=models.FileField(blank=True, help_text='The actual PowerPoint file downloaded from GeoIQ', null=True, upload_to='approved_stores/ppts/%Y/%m/', verbose_name='Downloaded PPTX'),
        ),
        migrations.AddField(
            model_name='approvedlenskartstore',
            name='ppt_url_raw',
            field=models.URLField(blank=True, help_text='The CDN link provided by the API', max_length=2000, null=True, verbose_name='Original PPT URL'),
        ),
        migrations.AddField(
            model_name='approvedlenskartstore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='approvedlenskartstore',
            name='market_ids_raw',
            field=models.TextField(blank=True, help_text='Comma or semicolon separated IDs from API', null=True, verbose_name='Raw Market IDs (CSV)'),
        ),
        migrations.AlterField(
            model_name='approvedlenskartstore',
            name='property_id',
            field=models.IntegerField(help_text='Unique identifier from GeoIQ/Kissflow', unique=True, verbose_name='Property ID'),
        ),
        migrations.AlterField(
            model_name='approvedlenskartstore',
            name='source_ppt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stores', to='property.propertyrecord', verbose_name='Source PPT Mapping'),
        ),
    ]
