# Generated by Django 6.0.1 on 2026-01-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_approvedlenskartstore_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedlenskartstore',
            name='catchments',
        ),
        migrations.RemoveField(
            model_name='approvedlenskartstore',
            name='source_ppt',
        ),
        migrations.AlterField(
            model_name='approvedlenskartstore',
            name='kissflow_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kissflow Status'),
        ),
        migrations.AlterField(
            model_name='approvedlenskartstore',
            name='market_ids_raw',
            field=models.TextField(blank=True, help_text='Original market ID data from API', null=True, verbose_name='Raw Market IDs'),
        ),
        migrations.AlterField(
            model_name='approvedlenskartstore',
            name='ppt_file',
            field=models.FileField(blank=True, null=True, upload_to='approved_stores/ppts/%Y/%m/', verbose_name='Downloaded PPTX'),
        ),
        migrations.AlterField(
            model_name='approvedlenskartstore',
            name='ppt_url_raw',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Original PPT URL'),
        ),
    ]
