# Generated by Django 6.0.1 on 2026-01-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_approvedlenskartstore_catchments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedlenskartstore',
            name='market_ids_raw',
        ),
        migrations.AddField(
            model_name='approvedlenskartstore',
            name='latest_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvedlenskartstore',
            name='market_id',
            field=models.CharField(blank=True, help_text='Raw Market IDs (e.g. 33441; 33442)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='approvedlenskartstore',
            name='market_name',
            field=models.TextField(blank=True, help_text='Full path of the market/catchment', null=True),
        ),
        migrations.AddField(
            model_name='approvedlenskartstore',
            name='property_created_by_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='approvedlenskartstore',
            name='survey_filled_by_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='approvedlenskartstore',
            name='kissflow_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='approvedlenskartstore',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='approvedlenskartstore',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='approvedlenskartstore',
            name='ppt_file',
            field=models.FileField(blank=True, null=True, upload_to='approved_stores/ppts/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='approvedlenskartstore',
            name='ppt_url_raw',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='approvedlenskartstore',
            name='property_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approvedlenskartstore',
            name='property_id',
            field=models.IntegerField(unique=True, verbose_name='Property ID'),
        ),
        migrations.AlterField(
            model_name='approvedlenskartstore',
            name='property_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
