# Generated by Django 6.0.1 on 2026-01-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_approvedlenskartstore_market_ids_raw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedlenskartstore',
            name='ceiling_height',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='approvedlenskartstore',
            name='frontage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='approvedlenskartstore',
            name='geoiq_projected_revenue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='approvedlenskartstore',
            name='height_from_beam_bottom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='approvedlenskartstore',
            name='proposed_rent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='approvedlenskartstore',
            name='signage_height',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='approvedlenskartstore',
            name='signage_width',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='approvedlenskartstore',
            name='store_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='approvedlenskartstore',
            name='trade_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
