# Generated by Django 6.0.1 on 2026-01-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_approvedlenskartstore_ceiling_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedlenskartstore',
            name='first_slide_image',
            field=models.ImageField(blank=True, null=True, upload_to='approved_stores/slides/%Y/%m/', verbose_name='First Slide Preview'),
        ),
        migrations.AlterField(
            model_name='approvedlenskartstore',
            name='market_id',
            field=models.CharField(blank=True, help_text='Raw Market IDs', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='approvedlenskartstore',
            name='market_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
