# Generated by Django 6.0.1 on 2026-01-13 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_alter_propertyrecord_options_and_more'),
        ('store', '0009_remove_approvedlenskartstore_source_ppt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedlenskartstore',
            name='source_ppt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stores', to='property.propertyrecord', verbose_name='Source Property Record'),
        ),
        migrations.AlterField(
            model_name='approvedlenskartstore',
            name='market_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='approvedlenskartstore',
            name='market_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
