# Generated by Django 6.0.1 on 2026-01-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_approvedlenskartstore_source_ppt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedlenskartstore',
            name='market_id',
            field=models.CharField(blank=True, help_text='Raw Market IDs', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='approvedlenskartstore',
            name='market_name',
            field=models.TextField(blank=True, help_text='Full path of the market', null=True),
        ),
    ]
