# Generated by Django 6.0.1 on 2026-01-08 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catchment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_id', models.IntegerField(unique=True, verbose_name='Market ID')),
                ('market_name', models.CharField(max_length=255, verbose_name='Market Name')),
                ('additional_info', models.TextField(verbose_name='Additional Info')),
                ('zone', models.CharField(max_length=100)),
                ('wkt_geometry', models.TextField(verbose_name='WKT Geometry')),
                ('created_at', models.DateTimeField(verbose_name='Created At')),
                ('hub_name', models.CharField(max_length=100, verbose_name='Hub Name')),
                ('circle', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('centroid', models.CharField(blank=True, max_length=50, null=True, verbose_name='Calculated Centroid (Lat, Lon)')),
                ('market_level_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Market Level Name')),
                ('rank_hub', models.IntegerField(blank=True, null=True, verbose_name='Hub Rank')),
                ('total_hubs', models.IntegerField(blank=True, null=True, verbose_name='Total Hubs in Circle')),
                ('rank_city', models.IntegerField(blank=True, null=True, verbose_name='City Rank')),
                ('total_city', models.IntegerField(blank=True, null=True, verbose_name='Total Cities in Hub')),
                ('has_store', models.BooleanField(default=False, verbose_name='Has Associated Lenskart Store')),
            ],
            options={
                'verbose_name_plural': 'Catchments',
                'db_table': 'catchments',
            },
        ),
        migrations.CreateModel(
            name='ApprovedLenskartStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField(unique=True, verbose_name='Property ID')),
                ('property_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Property Name')),
                ('property_address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='Longitude')),
                ('market_ids_raw', models.TextField(blank=True, null=True, verbose_name='Raw Market IDs (CSV)')),
                ('kissflow_status', models.CharField(max_length=50, verbose_name='Kissflow Status')),
                ('catchments', models.ManyToManyField(related_name='approved_lenskart_stores', to='catchment.catchment', verbose_name='Mapped Catchments')),
            ],
            options={
                'verbose_name_plural': 'Approved Lenskart Stores',
                'db_table': 'approved_lenskart_store',
            },
        ),
        migrations.CreateModel(
            name='LenskartStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_code', models.CharField(max_length=50, unique=True, verbose_name='Store Code')),
                ('store_name', models.CharField(max_length=255, verbose_name='Store Name')),
                ('store_address', models.TextField(blank=True, null=True, verbose_name='Store Address')),
                ('finance_op_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='Finance Op.Date')),
                ('opening_month', models.CharField(blank=True, max_length=50, null=True, verbose_name='OPENING MONTH')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='STATUS')),
                ('store_close_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='Store Close Date')),
                ('proto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Proto')),
                ('rent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('format', models.CharField(blank=True, max_length=50, null=True, verbose_name='Format')),
                ('fy', models.CharField(blank=True, max_length=50, null=True, verbose_name='FY')),
                ('area', models.CharField(blank=True, max_length=50, null=True, verbose_name='Area')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('tier', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tier')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Region')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('google_maps_link', models.TextField(blank=True, null=True, verbose_name='Google Maps Link')),
                ('metrics_data', models.JSONField(default=dict, verbose_name='Monthly Performance Metrics')),
                ('catchment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapped_stores', to='catchment.catchment', verbose_name='Mapped Catchment')),
            ],
            options={
                'verbose_name_plural': 'Lenskart Stores',
                'db_table': 'lenskart_store',
            },
        ),
    ]
