# Generated by Django 6.0.1 on 2026-01-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catchment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lenskartstore',
            name='catchment',
        ),
        migrations.DeleteModel(
            name='ApprovedLenskartStore',
        ),
        migrations.DeleteModel(
            name='LenskartStore',
        ),
    ]
