# Generated by Django 6.0.1 on 2026-01-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.CharField(max_length=20)),
                ('weekly_date', models.CharField(max_length=50)),
                ('property_approval_status', models.CharField(choices=[('Approved', 'Approved'), ('Dropped', 'Dropped'), ('Hold', 'Hold'), ('Conditionally Approved', 'Conditionally Approved')], db_index=True, max_length=50)),
                ('zone', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('folder_id', models.CharField(max_length=255, unique=True)),
                ('ppt_link', models.URLField(blank=True, max_length=500, null=True)),
                ('notes_link', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVE', 'Approve'), ('DROP', 'Drop')], db_index=True, default='PENDING', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Property Records',
                'ordering': ['-year', '-weekly_date', 'zone'],
            },
        ),
    ]
