# Generated by Django 6.0.1 on 2026-01-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(blank=True, max_length=50, null=True)),
                ('presentation_date_context', models.CharField(max_length=255)),
                ('ppt_link', models.URLField(blank=True, max_length=500, null=True)),
                ('ai_summary_link', models.URLField(blank=True, max_length=500, null=True)),
                ('recording_link', models.URLField(blank=True, max_length=500, null=True)),
                ('first_slide_image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('Approved', 'Approved'), ('Dropped/Rejected', 'Dropped/Rejected'), ('Conditionally Approved', 'Conditionally Approved'), ('Hold', 'Hold')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
