# Generated by Django 6.0.1 on 2026-01-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Property Record', 'verbose_name_plural': 'Property Records'},
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='frontage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='lk_stores',
            field=models.TextField(blank=True, help_text='Comma-separated list of LKST codes found in PPT', null=True),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='projected_revenue_lakhs',
            field=models.CharField(blank=True, help_text='Extracted GeoIQ Revenue Projection', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='store_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='total_rent_maintenance',
            field=models.CharField(blank=True, help_text='Extracted Rent + Maintenance', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='trade_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
