# Generated by Django 6.0.1 on 2026-01-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyrecord',
            options={},
        ),
        migrations.RenameField(
            model_name='propertyrecord',
            old_name='name',
            new_name='presentation_date_context',
        ),
        migrations.RemoveField(
            model_name='propertyrecord',
            name='folder_id',
        ),
        migrations.RemoveField(
            model_name='propertyrecord',
            name='month',
        ),
        migrations.RemoveField(
            model_name='propertyrecord',
            name='notes_link',
        ),
        migrations.RemoveField(
            model_name='propertyrecord',
            name='property_approval_status',
        ),
        migrations.RemoveField(
            model_name='propertyrecord',
            name='weekly_date',
        ),
        migrations.RemoveField(
            model_name='propertyrecord',
            name='year',
        ),
        migrations.RemoveField(
            model_name='propertyrecord',
            name='zone',
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='ppt_link',
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVE', 'Approve'), ('DROP', 'Drop')], default='PENDING', max_length=10),
        ),
    ]
