# Generated by Django 6.0.1 on 2026-01-13 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_propertyrecord_options_propertyrecord_frontage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyrecord',
            name='frontage',
        ),
        migrations.RemoveField(
            model_name='propertyrecord',
            name='lk_stores',
        ),
        migrations.RemoveField(
            model_name='propertyrecord',
            name='store_size',
        ),
        migrations.RemoveField(
            model_name='propertyrecord',
            name='trade_area',
        ),
    ]
