# Generated by Django 6.0.1 on 2026-01-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_propertyrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrecord',
            name='ai_summary_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='recording_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
