# Generated by Django 6.0.1 on 2026-01-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_propertyrecord_frontage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyrecord',
            options={},
        ),
        migrations.RemoveField(
            model_name='propertyrecord',
            name='presentation_date_context',
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='market_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='zone_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
