# Generated by Django 6.0.1 on 2026-01-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_propertyrecord_ai_summary_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrecord',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
    ]
