# Generated by Django 6.0.1 on 2026-01-12 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_propertyrecord_latitude_propertyrecord_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyrecord',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='propertyrecord',
            name='longitude',
        ),
    ]
