# Generated by Django 6.0.1 on 2026-01-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_propertyrecord_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyrecord',
            old_name='market_name',
            new_name='final_market_name',
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='circle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='city_rank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='hub',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='hub_rank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='projected_revenue_lakhs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='total_rent_maintenance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
