# Generated by Django 6.0.1 on 2026-01-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_remove_propertyrecord_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrecord',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
