# Generated by Django 6.0.1 on 2026-01-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_rename_market_name_propertyrecord_final_market_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Property Record', 'verbose_name_plural': 'Property Records'},
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
