# Generated by Django 6.0.1 on 2026-01-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_propertyrecord_options_propertyrecord_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrecord',
            name='date_presented',
            field=models.DateField(blank=True, null=True),
        ),
    ]
