# Generated by Django 6.0.1 on 2026-01-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_propertyrecord_latitude_propertyrecord_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyrecord',
            options={'verbose_name': 'Property Record', 'verbose_name_plural': 'Property Records'},
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='market_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
    ]
