# Generated by Django 6.0.1 on 2026-01-12 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_propertyrecord_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyrecord',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='propertyrecord',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='propertyrecord',
            name='market_name',
        ),
    ]
