# Generated by Django 6.0.1 on 2026-01-14 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_propertyrecord_date_presented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyrecord',
            name='date_presented',
        ),
    ]
