# Generated by Django 6.0.1 on 2026-01-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_remove_propertyrecord_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyrecord',
            options={},
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
