# Generated by Django 5.2.5 on 2026-01-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_remove_propertyrecord_date_presented'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyrecord',
            options={'ordering': ['-presentation_date', '-created_at'], 'verbose_name': 'Property Record', 'verbose_name_plural': 'Property Records'},
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='presentation_date',
            field=models.DateField(blank=True, help_text='Extracted from Google Drive folder hierarchy', null=True),
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='ai_summary_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='final_market_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='first_slide_image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='ppt_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='recording_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
