# Generated by Django 6.0.1 on 2026-01-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_propertyrecord_options_propertyrecord_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyrecord',
            options={'verbose_name': 'Property Record', 'verbose_name_plural': 'Property Records'},
        ),
        migrations.RemoveField(
            model_name='propertyrecord',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='propertyrecord',
            name='longitude',
        ),
    ]
