# Generated by Django 6.0.1 on 2026-01-13 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_alter_propertyrecord_options_propertyrecord_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyrecord',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='propertyrecord',
            name='longitude',
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='property_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='ppt_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
