# Generated by Django 6.0.1 on 2026-01-13 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_remove_propertyrecord_latitude_and_more'),
        ('store', '0012_alter_approvedlenskartstore_market_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Property Record', 'verbose_name_plural': 'Property Records'},
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='approved_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_records', to='store.approvedlenskartstore', verbose_name='Linked Approved Store'),
        ),
    ]
