# Generated by Django 6.0.1 on 2026-01-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_alter_propertyrecord_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyrecord',
            name='approved_store',
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
