# Generated by Django 6.0.1 on 2026-01-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_remove_propertyrecord_approved_store_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyrecord',
            options={},
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='property_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Approved', 'Approved'), ('Dropped/Rejected', 'Dropped/Rejected'), ('Conditionally Approved', 'Conditionally Approved'), ('Hold', 'Hold')], default='pending', max_length=50),
        ),
    ]
