# Generated by Django 6.0.1 on 2026-01-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_propertyrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrecord',
            name='first_slide_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_slides/'),
        ),
    ]
