# Generated by Django 6.0.1 on 2026-01-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_propertyrecord_first_slide_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyrecord',
            name='first_slide_image',
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='first_slide_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
